spring.application.name=ms-orders
server.port=${SERVER_PORT:8083}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/pulpapp_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

ms-products.base-url=${MS_PRODUCTS_BASE_URL:http://localhost:8082}
